Numpy and Arrays

In [2]:
from re import S
import numpy as np

z = np.zeros(5)

print(z)


[0. 0. 0. 0. 0.]


In [3]:
np.shape(z)

(5,)

In [4]:
z2= np.zeros((4,5))
print(z2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
f=np.full((7,8),11)
print(f)

[[11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11 11]]


In [6]:
np.shape(f)

(7, 8)

In [7]:
x=np.linspace(0,5,10)
print(x)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [8]:
x2=np.arange(0,5,0.2)
print(x2)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


In [9]:
a = 1
b = 6
amount = 50
nopat = np.random.randint(a,b+1,amount)
print(nopat)

[2 6 2 4 3 1 6 3 2 4 6 6 1 6 5 6 4 6 2 4 4 5 5 6 6 3 6 2 2 6 2 1 4 1 1 3 3
 1 1 2 2 1 4 6 5 4 3 1 2 3]


In [10]:
xx = np.random.randn(10)
print(xx)

[-0.02647892 -0.22019343 -1.52543624 -0.69358163  0.87768593  1.12949845
  0.07023884 -1.69713736  0.43004979 -1.34446935]


In [11]:
xx.ndim

1

In [12]:
xx.size

10

In [13]:
xx = np.random.random(10)
print(xx)

[0.77701278 0.52136136 0.78826552 0.54449276 0.86303875 0.74896886
 0.77440781 0.14625022 0.6394465  0.08260136]


In [14]:
#data = np.genfromtext("data.csv",delimeter=",",skip_header=1)

Cutting Matrices (indexing)

In [15]:
A = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(A)
np.shape(A)
A.reshape(2,3,2)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
A = np.repeat([[1,2,3]],4,axis=0)
print(A)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [17]:
B = np.repeat([[1],[2],[3]],3,axis=1)
print(B)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [18]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [19]:
print(A[0,0])
print(A[0,1])

1
2


In [20]:
A[:,0]

array([1, 4])

In [21]:
A[0,:]

array([1, 2, 3])

In [22]:
new = np.vstack((A,A))
print(new)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [23]:
new2 = np.hstack((A,A))
print(new2)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [24]:
B = np.delete(A,[0],0)

print(B)


[[4 5 6]]


In [25]:
C = np.delete(A,[1],1)
print(C)

[[1 3]
 [4 6]]


In [26]:
A = np.array([1,2,3,4,5,6])
print(A)
A = A.reshape(2,3)
print(A)
n,m = np.shape(A)
for i in range(n):
    print("Row",i,"on",A[i,:])

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
Row 0 on [1 2 3]
Row 1 on [4 5 6]


In [27]:
for j in range(m): 
    print("Column",j,"on",A[:,j])

Column 0 on [1 4]
Column 1 on [2 5]
Column 2 on [3 6]


In [28]:
for i in range(n):
    for j in range(m):
        print("Element",i,j,"on",A[i,j])

Element 0 0 on 1
Element 0 1 on 2
Element 0 2 on 3
Element 1 0 on 4
Element 1 1 on 5
Element 1 2 on 6


In [29]:
for a in np.nditer(A):
    print(a)

1
2
3
4
5
6


Calculations with Matrices


In [30]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,9],[4,-1]])
A+B


array([[ 4, 11],
       [ 7,  3]])

In [31]:
A-B

array([[-2, -7],
       [-1,  5]])

In [32]:
A*B

array([[ 3, 18],
       [12, -4]])

In [33]:
A/B

array([[ 0.33333333,  0.22222222],
       [ 0.75      , -4.        ]])

In [34]:
A @ B

array([[11,  7],
       [25, 23]])

In [35]:
A.dot(B)
#np.matmul(A,B)

array([[11,  7],
       [25, 23]])

In [36]:
np.all(A>1)

False

In [37]:
np.any(A>1)

True

In [39]:
A = np.array([1,2,3,4,5,6,7])
B = A[A>3]
print(A)

[1 2 3 4 5 6 7]


In [40]:
print(B)

[4 5 6 7]


In [42]:
A = np.array([[2,1],[-4,3]])
b = np.array([11,3])
X = np.linalg.solve(A,b)
print(X)

[3. 5.]


In [44]:
AA = np.linalg.inv(A)
print(np.matmul(AA,b))

[3. 5.]


Statistical Functions

In [46]:
A = np.array([[1,2,3],[4,5,6]])
np.sum(A)


21

In [47]:
np.sum(A,0) # column sums, summed along rows


array([5, 7, 9])

In [48]:
np.sum(A,1) # row sums, summed along the columns

array([ 6, 15])

In [49]:
#The product is calculated similarly with the prod () command.

np.prod(A)
np.prod(A,0)
np.prod(A,1)

array([  6, 120])

Data Types

In [54]:
A = np.array([1,2,3,4,5,6],dtype="int8")
A.dtype

dtype('int8')

In [56]:
A.itemsize

1

In [57]:
A.nbytes

6

In [59]:
A = np.array([1,2,3,4,5,6],dtype="int64")
A.nbytes

48

int8	-128...127

int16	-32768...32767

int32	-2147483648...2147483647

int64	-9223372036854775808...9223372036854775807

uint8	0...255

uint16	0...65535

uint32	0...4294967295

uint64	0...18446744073709551615

In [62]:
print(str.format('{0:.2f}', 1/3))

0.33


In [63]:
0.1+0.1+0.1+0.1+0.1+0.1+0.1+0.1

0.7999999999999999

In [64]:
print(str.format('{0:.10f}', 0.1))


0.1000000000
